export const GET_PROJECTS = "GET_PROJECTS"

export const GET_PROJECT_DETAILS="GET_PROJECT_DETAILS"

export const GET_MY_DETAILS ="GET_MY_DETAILS"

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const GET_SOCIAL_LINKES = "GET_SOCIAL_LINKES"

export const SEND_CONTACT_REQUEST = 'SEND_CONTACT_REQUEST';
export const SEND_CONTACT_SUCCESS = 'SEND_CONTACT_SUCCESS';
export const SEND_CONTACT_FAILURE = 'SEND_CONTACT_FAILURE';
